---
extends: [standard, prettier, prettier/standard]
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
rules:
  comma-dangle: [2, always-multiline]
globals:
  Phaser: false
  PIXI: false
