module.exports = [
  {
    initials: 'SNM',
    score: 10,
    lives: 2,
    level: 13,
    avatar: 'default',
    avatarData: null,
    won: true,
  },
  {
    initials: 'JSF',
    score: 9,
    lives: 0,
    level: 8,
    avatar: 'josef',
    avatarData: null,
    won: true,
  },
  {
    initials: 'DIT',
    score: 8,
    lives: 0,
    level: 7,
    avatar: 'dita',
    avatarData: null,
  },
  {
    initials: 'KUB',
    score: 7,
    lives: 0,
    level: 7,
    avatar: 'jakub',
    avatarData: null,
  },
  {
    initials: 'DAN',
    score: 6,
    lives: 0,
    level: 5,
    avatar: 'dan',
    avatarData: null,
  },
  {
    initials: 'MAR',
    score: 5,
    lives: 0,
    level: 4,
    avatar: 'marta',
    avatarData: null,
  },
  {
    initials: 'FRA',
    score: 4,
    lives: 0,
    level: 4,
    avatar: 'frantisek',
    avatarData: null,
  },
  {
    initials: 'JNV',
    score: 3,
    lives: 0,
    level: 4,
    avatar: 'honza',
    avatarData: null,
  },
  {
    initials: 'JAK',
    score: 2,
    lives: 0,
    level: 4,
    avatar: 'jak',
    avatarData: null,
  },
  {
    initials: 'TYN',
    score: 1,
    lives: 0,
    level: 4,
    avatar: 'tyna',
    avatarData: null,
  },
]
