module.exports = [
  {
    initials: 'SNM',
    score: 9001,
    lives: 2,
    level: 13,
    avatar: 'default',
    avatarData: null,
    won: true,
  },
  {
    initials: 'JSF',
    score: 2000,
    lives: 0,
    level: 8,
    avatar: 'josef',
    avatarData: null,
    won: true,
  },
  {
    initials: 'DIT',
    score: 1500,
    lives: 0,
    level: 7,
    avatar: 'dita',
    avatarData: null,
  },
  {
    initials: 'KUB',
    score: 1000,
    lives: 0,
    level: 7,
    avatar: 'jakub',
    avatarData: null,
  },
  {
    initials: 'DAN',
    score: 500,
    lives: 0,
    level: 5,
    avatar: 'dan',
    avatarData: null,
  },
  {
    initials: 'MAR',
    score: 400,
    lives: 0,
    level: 4,
    avatar: 'marta',
    avatarData: null,
  },
  {
    initials: 'FRA',
    score: 300,
    lives: 0,
    level: 4,
    avatar: 'frantisek',
    avatarData: null,
  },
  {
    initials: 'JNV',
    score: 200,
    lives: 0,
    level: 4,
    avatar: 'honza',
    avatarData: null,
  },
  {
    initials: 'JAK',
    score: 100,
    lives: 0,
    level: 4,
    avatar: 'jak',
    avatarData: null,
  },
  {
    initials: 'TYN',
    score: 50,
    lives: 0,
    level: 4,
    avatar: 'tyna',
    avatarData: null,
  },
]
